### ISSUE TITLE
Autoformatter should move first branch of matching to the right

### ISSUE THREAD

**Issue by Kakadu** [Mervap/LamaPlugin#17]
To be in sync with Haskell and OCaml syntax autoformatters. 

Currently it places first branch above bar symbol, which is weird.

![image](https://user-images.githubusercontent.com/438226/192474852-98b0a6c5-74ae-4d71-bda9-6be1866be2f9.png)

**Comment by Mervap** [comment]
There are such option in formatter settings
Do you think it should be enabled by default?
<img width="600" alt="image" src="https://user-images.githubusercontent.com/31941254/192878743-777d9270-1a31-45f6-b2cb-8ed1117b2ad1.png">

**Comment by Kakadu** [comment]
Yes, it definitely should. Thanks!

**Comment by Mervap** [comment]
Fixed in [v0.2.5](https://github.com/Mervap/LamaPlugin/releases/tag/v0.2.5)
